// <auto-generated />
using System;
using CNCLib.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CNCLib.Repository.SqLite.Migrations
{
    [DbContext(typeof(CNCLibContext))]
    partial class CNCLibContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Configuration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4000);

                    b.HasKey("ConfigurationId");

                    b.HasIndex("UserId", "Group", "Name")
                        .IsUnique();

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.ItemProperty", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "Name");

                    b.ToTable("ItemProperty");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Axis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BufferSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComPort")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<int>("CommandSyntax")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CommandToUpper")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Coolant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DtrIsReset")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Laser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<bool>("NeedDtr")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProbeDist")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProbeDistUp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProbeFeed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProbeSizeX")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProbeSizeY")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProbeSizeZ")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rotate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SDSupport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialServer")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialServerPassword")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<int>("SerialServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialServerProtocol")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("SerialServerUser")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<decimal>("SizeA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeX")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeY")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SizeZ")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Spindle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.MachineCommand", b =>
                {
                    b.Property<int>("MachineCommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("CommandString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("JoystickMessage")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PosX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PosY")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineCommandId");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineCommand");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.MachineInitCommand", b =>
                {
                    b.Property<int>("MachineInitCommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeqNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineInitCommandId");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineInitCommand");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128)
                        .IsUnicode(true);

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255)
                        .IsUnicode(true);

                    b.HasKey("UserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.UserFile", b =>
                {
                    b.Property<int>("UserFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(1024)
                        .IsUnicode(true);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserFileId");

                    b.HasIndex("UserId", "FileName")
                        .IsUnique();

                    b.ToTable("UserFile");
                });

            modelBuilder.Entity("Framework.Repository.Abstraction.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .IsUnicode(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logger")
                        .HasColumnType("TEXT")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64)
                        .IsUnicode(true);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsUnicode(true);

                    b.Property<string>("Port")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256)
                        .IsUnicode(true);

                    b.Property<string>("RemoteAddress")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("ServerAddress")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64)
                        .IsUnicode(true);

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT")
                        .IsUnicode(true);

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Configuration", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Item", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.ItemProperty", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.Item", "Item")
                        .WithMany("ItemProperties")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.Machine", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.MachineCommand", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.Machine", "Machine")
                        .WithMany("MachineCommands")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.MachineInitCommand", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.Machine", "Machine")
                        .WithMany("MachineInitCommands")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNCLib.Repository.Abstraction.Entities.UserFile", b =>
                {
                    b.HasOne("CNCLib.Repository.Abstraction.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
