
name: CNCLib.Server Docker (for Raspberry/Linux)

env:
  ContainerName: cnclibserver      # Name of he (docker-)container
  SolutionPath: Src                # sub-directory of sln file location
  SolutionName: CNCLib.sln         # Replace with your solution name, i.e. MyWpfApp.sln.
  AppProject: Server/Server.csproj # Replace with the path to your app project, i.e. MyWpfApp\MyWpfApp.csproj.

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: self-hosted

    steps:
     
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          #context: "{{defaultContext}}:Src"
          context: ./Src
          file: ./Src/Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ContainerName}}:latest
          
